"""NAMD checkpoint-restart config generator.

Generates a NAMD restart configuration from checkpoint files (.restart.coor,
.restart.vel, .restart.xsc) so that a preempted simulation can resume from
the last checkpoint instead of starting over.

Usage:
    from cloudcomputemanager.checkpoint.namd_restart import generate_restart_config

    result = generate_restart_config(
        restart_xsc="simulation.restart.xsc",
        total_steps=15150000,
        target_temp=453,
    )
    print(result["config"])         # NAMD config text
    print(result["step_number"])    # e.g., 5000000
    print(result["remaining"])      # e.g., 10150000
"""

from pathlib import Path
from typing import Optional
import structlog

logger = structlog.get_logger()


def parse_xsc_step(xsc_path: str) -> int:
    """Extract step number from NAMD .xsc restart file.

    The .xsc file format:
        # NAMD extended system configuration restart file
        #$LABELS step a_x a_y a_z b_x b_y b_z c_x c_y c_z o_x o_y o_z
        500000 72.95 0 0 0 72.95 0 0 0 72.95 36.475 36.475 36.475

    Returns:
        Step number (int)
    """
    with open(xsc_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("#") or not line:
                continue
            return int(line.split()[0])
    raise ValueError(f"Could not parse step number from {xsc_path}")


def generate_restart_config(
    restart_xsc: str,
    total_steps: int = 15300000,
    target_temp: float = 453.0,
    structure: str = "inputs/4HPt.psf",
    coordinates: str = "snapshot_coords.pdb",
    parameters: str = "inputs/IFF_CHARMM36_parameters_V9_NEC.prm",
    restart_coor: str = "simulation.restart.coor",
    restart_vel: str = "simulation.restart.vel",
    restart_xsc_ref: str = "simulation.restart.xsc",
    output_name: str = "simulation",
    dcdfreq: int = 10000,
    restartfreq: int = 50000,
) -> dict:
    """Generate a NAMD restart configuration.

    Args:
        restart_xsc: Path to .xsc file (for step number extraction)
        total_steps: Total steps for the entire simulation (cooling + production)
        target_temp: Production temperature (K)
        structure: Path to PSF file
        coordinates: Path to PDB file (for structure definition)
        parameters: Path to force field parameter file
        restart_coor: Path to binary coordinate restart file
        restart_vel: Path to binary velocity restart file
        output_name: Base name for output files
        dcdfreq: DCD write frequency
        restartfreq: Restart file write frequency

    Returns:
        dict with keys:
            config: str — NAMD config file content
            step_number: int — step number from checkpoint
            remaining: int — remaining steps to run
            in_cooling: bool — whether checkpoint is in cooling phase
    """
    step_number = parse_xsc_step(restart_xsc)

    # Cooling schedule: 14 steps × 150,000 + 400,000 equilibration = 2,500,000 steps
    COOLING_STEPS = 2500000
    STEPS_PER_TEMP = 150000
    NUM_COOLING_STEPS = 14
    EQUILIBRATION_STEPS = 400000
    START_TEMP = 1000
    in_cooling = step_number < COOLING_STEPS

    remaining = total_steps - step_number
    if remaining <= 0:
        logger.info("Simulation already complete", step=step_number, total=total_steps)
        return {
            "config": None,
            "step_number": step_number,
            "remaining": 0,
            "in_cooling": False,
        }

    # Common header for both cooling and production restarts
    header = f"""#############################################################
## NAMD RESTART CONFIGURATION — Generated by CCM Recovery
##
## Resuming from step {step_number} ({'COOLING' if in_cooling else 'PRODUCTION'} phase)
## Remaining: {remaining} steps ({remaining * 1e-6:.2f} ns)
## Target temperature: {target_temp} K
#############################################################

# Structure definition (required for NAMD parsing)
structure           {structure}
coordinates         {coordinates}

# Load checkpoint — overrides PDB coordinates
binCoordinates      {restart_coor}
binVelocities       {restart_vel}
extendedSystem      {restart_xsc_ref}

# Step tracking for DCD timestamps
firsttimestep       {step_number}

# Force field
paraTypeCharmm      on
parameters          {parameters}

exclude             scaled1-4
1-4scaling          1.0
switching           on
switchdist          10.0
cutoff              12.0
pairlistdist        14.0

PME                 yes
PMEGridSpacing      1.0

# PBC from extendedSystem (no cellBasisVector needed)
wrapAll             on
wrapNearest         on

# Integration
timestep            1.0
rigidBonds          water
nonbondedFreq       1
fullElectFrequency  2
stepspercycle       10

# Output
outputName          {output_name}
binaryoutput        yes
binaryrestart       yes
dcdfreq             {dcdfreq}
outputEnergies      5000
outputTiming        50000
restartfreq         {restartfreq}
xstFreq             {dcdfreq}

# Thermostat
langevin            on
langevinDamping     1.0
langevinHydrogen    off
"""

    if in_cooling:
        # Determine where we are in the cooling schedule
        # Each temp step = STEPS_PER_TEMP (150,000). After 14 steps, 400k equilibration.
        temp_step = float(START_TEMP - target_temp) / NUM_COOLING_STEPS
        cooling_main_end = NUM_COOLING_STEPS * STEPS_PER_TEMP  # 2,100,000

        if step_number < cooling_main_end:
            # In the cooling ramp — figure out which temp step we're at
            completed_steps = step_number // STEPS_PER_TEMP
            remaining_in_current = STEPS_PER_TEMP - (step_number % STEPS_PER_TEMP)
            current_temp = START_TEMP - completed_steps * temp_step

            cooling_body = f"""
# Resume cooling from step {completed_steps}/{NUM_COOLING_STEPS} (T={current_temp:.0f} K)
langevinTemp        {current_temp}
reassignFreq        500
reassignIncr        0
reassignHold        0

print "===== CCM RECOVERY: Resuming COOLING from step {step_number} ====="
print "Cooling step {completed_steps}/{NUM_COOLING_STEPS}, T = {current_temp:.0f} K"

# Finish current temperature step
reassignTemp {current_temp}
run {remaining_in_current}
"""
            # Remaining cooling steps
            for i in range(int(completed_steps) + 1, NUM_COOLING_STEPS + 1):
                t = START_TEMP - i * temp_step
                cooling_body += f"""
reassignTemp {t:.0f}
print "COOLING: Step {i}/{NUM_COOLING_STEPS}, T = {t:.0f} K"
run {STEPS_PER_TEMP}
"""
            # Final equilibration
            cooling_body += f"""
# Final equilibration at {target_temp} K
print "COOLING: Final equilibration at {target_temp} K"
reassignTemp {target_temp}
langevinTemp {target_temp}
run {EQUILIBRATION_STEPS}

print "===== COOLING COMPLETE ====="
"""
        else:
            # In the equilibration phase after cooling ramp
            remaining_equil = COOLING_STEPS - step_number
            current_temp = target_temp
            cooling_body = f"""
# Resume equilibration at {target_temp} K
langevinTemp        {target_temp}
reassignFreq        500
reassignIncr        0
reassignHold        0
reassignTemp        {target_temp}

print "===== CCM RECOVERY: Resuming EQUILIBRATION from step {step_number} ====="
run {remaining_equil}

print "===== COOLING COMPLETE ====="
"""

        # Production phase after cooling
        production_steps = total_steps - COOLING_STEPS
        cooling_body += f"""
#############################################################
## PRODUCTION — {production_steps} steps ({production_steps * 1e-6:.2f} ns) @ {target_temp} K
#############################################################

print "===== STAGE 2: PRODUCTION ====="
run {production_steps}

print "===== PRODUCTION COMPLETE ====="
"""
        config = header + cooling_body

        logger.info(
            "Generated NAMD COOLING restart config",
            step=step_number,
            cooling_step=step_number // STEPS_PER_TEMP,
            remaining=remaining,
        )
    else:
        # Production phase restart (original logic)
        production_remaining = total_steps - step_number
        config = header + f"""
langevinTemp        {target_temp}

#############################################################
## PRODUCTION — remaining {production_remaining} steps
#############################################################

print "===== CCM RECOVERY: Resuming PRODUCTION from step {step_number} ====="
print "Remaining: {production_remaining} steps"

run                 {production_remaining}

print "===== PRODUCTION COMPLETE ====="
"""
        logger.info(
            "Generated NAMD PRODUCTION restart config",
            step=step_number,
            remaining=production_remaining,
        )

    return {
        "config": config,
        "step_number": step_number,
        "remaining": remaining,
        "in_cooling": in_cooling,
    }


def generate_recovery_command(has_restart_config: bool) -> str:
    """Generate the command for a recovered NAMD job.

    If CCM generated a restart config (simulation_restart.namd), use it.
    Otherwise, fall back to fresh start.

    This runs on the Vast.ai instance — no CCM imports needed.
    """
    if has_restart_config:
        return (
            "cd /workspace && "
            "if [ -f simulation.dcd ]; then "
            "STEP=$(awk 'NR==3{print $1}' simulation.restart.xsc) && "
            "mv simulation.dcd simulation_before_${STEP}.dcd && "
            "echo \"Preserved DCD as simulation_before_${STEP}.dcd\"; "
            "fi && "
            "echo '=== CCM RECOVERY: Resuming from checkpoint ===' && "
            "namd3 +p8 +devices 0 simulation_restart.namd > job.log 2>&1"
        )
    else:
        return (
            "cd /workspace && "
            "bash validate_namd.sh && "
            "namd3 +p8 +devices 0 cooling_production_453K.namd > job.log 2>&1"
        )
