"""NAMD checkpoint-restart config generator.

Generates a NAMD restart configuration from checkpoint files (.restart.coor,
.restart.vel, .restart.xsc) so that a preempted simulation can resume from
the last checkpoint instead of starting over.

Usage:
    from cloudcomputemanager.checkpoint.namd_restart import generate_restart_config

    result = generate_restart_config(
        restart_xsc="simulation.restart.xsc",
        total_steps=15150000,
        target_temp=453,
    )
    print(result["config"])         # NAMD config text
    print(result["step_number"])    # e.g., 5000000
    print(result["remaining"])      # e.g., 10150000
"""

from pathlib import Path
from typing import Optional
import structlog

logger = structlog.get_logger()


def parse_xsc_step(xsc_path: str) -> int:
    """Extract step number from NAMD .xsc restart file.

    The .xsc file format:
        # NAMD extended system configuration restart file
        #$LABELS step a_x a_y a_z b_x b_y b_z c_x c_y c_z o_x o_y o_z
        500000 72.95 0 0 0 72.95 0 0 0 72.95 36.475 36.475 36.475

    Returns:
        Step number (int)
    """
    with open(xsc_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("#") or not line:
                continue
            return int(line.split()[0])
    raise ValueError(f"Could not parse step number from {xsc_path}")


def generate_restart_config(
    restart_xsc: str,
    total_steps: int = 15150000,
    target_temp: float = 453.0,
    structure: str = "inputs/4HPt.psf",
    coordinates: str = "inputs/4HPt.pdb",
    parameters: str = "inputs/IFF_CHARMM36_parameters_V9_NEC.prm",
    restart_coor: str = "simulation.restart.coor",
    restart_vel: str = "simulation.restart.vel",
    restart_xsc_ref: str = "simulation.restart.xsc",
    output_name: str = "simulation",
    dcdfreq: int = 10000,
    restartfreq: int = 50000,
    cooling_protocol: bool = True,
) -> dict:
    """Generate a NAMD restart configuration.

    Args:
        restart_xsc: Path to .xsc file (for step number extraction)
        total_steps: Total steps for the entire simulation (cooling + production)
        target_temp: Production temperature (K)
        structure: Path to PSF file
        coordinates: Path to PDB file (for structure definition)
        parameters: Path to force field parameter file
        restart_coor: Path to binary coordinate restart file
        restart_vel: Path to binary velocity restart file
        output_name: Base name for output files
        dcdfreq: DCD write frequency
        restartfreq: Restart file write frequency
        cooling_protocol: Whether the job runs the scripted cooling+production
            protocol (1000→453 K ramp over the first 2,500,000 steps). The ramp
            lives in the original protocol file and cannot be reproduced by a
            continuation config, so mid-cooling checkpoints restart from scratch.
            Constant-temperature jobs (NPT equilibration, plain production) set
            this False and can restart from any step.

    Returns:
        dict with keys:
            config: str — NAMD config file content
            step_number: int — step number from checkpoint
            remaining: int — remaining steps to run
            in_cooling: bool — whether checkpoint is in the campaign cooling
                phase (always False when cooling_protocol=False)
    """
    step_number = parse_xsc_step(restart_xsc)

    # Cooling: 14 steps × 150,000 + 400,000 equilibration = 2,500,000 steps.
    # Only meaningful for cooling_protocol jobs — a constant-T job has no
    # temperature schedule to break, so any checkpoint step is resumable.
    COOLING_STEPS = 2500000
    in_cooling = cooling_protocol and step_number < COOLING_STEPS

    if in_cooling:
        logger.warning(
            "Checkpoint is in cooling phase — will restart from scratch",
            step=step_number,
            cooling_end=COOLING_STEPS,
        )
        return {
            "config": None,
            "step_number": step_number,
            "remaining": total_steps - step_number,
            "in_cooling": True,
        }

    remaining = total_steps - step_number
    if remaining <= 0:
        logger.info("Simulation already complete", step=step_number, total=total_steps)
        return {
            "config": None,
            "step_number": step_number,
            "remaining": 0,
            "in_cooling": False,
        }

    config = f"""#############################################################
## NAMD RESTART CONFIGURATION — Generated by CCM Recovery
##
## Resuming from step {step_number}
## Remaining: {remaining} steps ({remaining * 1e-6:.2f} ns)
## Temperature: {target_temp} K
#############################################################

# Structure definition (required for NAMD parsing)
structure           {structure}
coordinates         {coordinates}

# Load checkpoint — overrides PDB coordinates
binCoordinates      {restart_coor}
binVelocities       {restart_vel}
extendedSystem      {restart_xsc_ref}

# Step tracking for DCD timestamps
firsttimestep       {step_number}

# Force field
paraTypeCharmm      on
parameters          {parameters}

exclude             scaled1-4
1-4scaling          1.0
switching           on
switchdist          10.0
cutoff              12.0
pairlistdist        14.0

PME                 yes
PMEGridSpacing      1.0

# PBC from extendedSystem (no cellBasisVector needed)
wrapAll             on
wrapNearest         on

# Integration
timestep            1.0
rigidBonds          water
nonbondedFreq       1
fullElectFrequency  2
stepspercycle       10

# Output
outputName          {output_name}
binaryoutput        yes
binaryrestart       yes
dcdfreq             {dcdfreq}
outputEnergies      5000
outputTiming        50000
restartfreq         {restartfreq}
xstFreq             {dcdfreq}

# Thermostat (continues from checkpoint state)
langevin            on
langevinDamping     1.0
langevinTemp        {target_temp}
langevinHydrogen    off

#############################################################
## PRODUCTION — remaining steps
#############################################################

print "===== CCM RECOVERY: Resuming from step {step_number} ====="
print "Remaining: {remaining} steps"

run                 {remaining}

print "===== PRODUCTION COMPLETE ====="
"""

    logger.info(
        "Generated NAMD restart config",
        step=step_number,
        remaining=remaining,
        total=total_steps,
    )

    return {
        "config": config,
        "step_number": step_number,
        "remaining": remaining,
        "in_cooling": False,
    }


def generate_recovery_command(has_restart_config: bool) -> str:
    """Generate the command for a recovered NAMD job.

    If CCM generated a restart config (simulation_restart.namd), use it.
    Otherwise, fall back to fresh start.

    This runs on the Vast.ai instance — no CCM imports needed.
    """
    if has_restart_config:
        return (
            "cd /workspace && "
            "if [ -f simulation.dcd ]; then "
            "STEP=$(awk 'NR==3{print $1}' simulation.restart.xsc) && "
            "mv simulation.dcd simulation_before_${STEP}.dcd && "
            "echo \"Preserved DCD as simulation_before_${STEP}.dcd\"; "
            "fi && "
            "echo '=== CCM RECOVERY: Resuming from checkpoint ===' && "
            "namd3 +p8 +devices 0 simulation_restart.namd > job.log 2>&1"
        )
    else:
        return (
            "cd /workspace && "
            "bash validate_namd.sh && "
            "namd3 +p8 +devices 0 cooling_production_453K.namd > job.log 2>&1"
        )
